version: '3.8'
services:
  db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: edtech
      MYSQL_USER: ${JDBC_DATABASE_USERNAME}
      MYSQL_PASSWORD: ${JDBC_DATABASE_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - web-edtech-network
  app:
    image: loct2205/edtech-dockerfile
#    build:
#      context: .
#      dockerfile: Dockerfile
    environment:
      SPRING_DATASOURCE_URL: ${JDBC_DATABASE_URL}
      SPRING_DATASOURCE_USERNAME: ${JDBC_DATABASE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${JDBC_DATABASE_PASSWORD}
      SECURITY_JWT_SECRET: ${SECURITY_JWT_SECRET}
      SPRING_MAIL_USERNAME: ${SPRING_MAIL_USERNAME}
      SPRING_MAIL_PASSWORD: ${SPRING_MAIL_PASSWORD}
      FFPROBE_PATH: ${FFPROBE_PATH}
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
      - web-edtech-network
networks:
  web-edtech-network:

volumes:
  db_data:
