apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-config
  namespace: {{ .Release.Namespace }}
data: 
  MYSQL_ROOT_PASSWORD: root
  MYSQL_DATABASE: edtech
  MYSQL_USER: user
  MYSQL_PASSWORD: password