
apiVersion: apps/v1
kind: Deployment
metadata:
  name: db
  namespace: {{ .Release.Namespace }}
  labels:
    app: db
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: db
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
        - name: db
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.targetPort }}
              protocol: TCP
          envFrom: 
            - configMapRef: 
                name: {{ .Release.Name }}-config
          volumeMounts:
            - name: mysql-storage
              mountPath: /var/lib/mysql
      volumes:
      - name: mysql-storage
        persistentVolumeClaim:
          claimName: {{ include "db-chart.fullname" . }}-pvc
        