apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "db-chart.fullname" . }}-pvc
  labels:
    app: {{ include "db-chart.name" . }}
    chart: {{ include "db-chart.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.persistence.size }}