apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-config
  namespace: {{ .Release.Namespace }}
data:
  SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/edtech
  SPRING_DATASOURCE_USERNAME: user
  SPRING_DATASOURCE_PASSWORD: password
  SPRING_MAIL_USERNAME: llong6412@gmail.com
  FFPROBE_PATH: /usr/bin/ffprobe
  VNPAY_URL: https://sandbox.vnpayment.vn/paymentv2/vpcpay.html
  VNPAY_RETURN_URL: /payments/vnpay-payment-return
  VNPAY_TMN_CODE: JDNL5GS7
