apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secret
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  SECURITY_JWT_SECRET: M2NmYTc2ZWYxNDkzN2MxYzBlYTUxOWY4ZmMwNTdhODBmY2QwNGE3NDIwZjhlOGJjZDBhNzU2N2MyNzJlMDA3Yg==
  SPRING_MAIL_PASSWORD: cG5hdmdhamZucWx0eGJmbA==
  VNPAY_HASH_SECRET: MkYySTAwSUlMRjdSN1ZXNEdHTVFPRjdHTlVJN0o5UVg=
