name: CI/CD Workflow

on:
  push:
    tags:
      - '*' 

jobs:
  backend-build:
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Create firebase.config.json
        run: |
          echo "${{ secrets.FIREBASE_CONFIG_JSON }}" | base64 -d > backend/src/main/resources/firebase.config.json

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build Docker image
        run: |
          cd backend
          TAG_NAME=${{ github.ref_name }}
          docker build . -t ${{ secrets.DOCKERHUB_USERNAME }}/edtech-dockerfile:${TAG_NAME}

      - name: Push Docker image to Docker Hub
        run: |
          cd backend
          TAG_NAME=${{ github.ref_name }}
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/edtech-dockerfile:${TAG_NAME}

  update-values:
    if: startsWith(github.ref, 'refs/tags/')
    needs: backend-build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with: 
          ref: main
      - name: Update values.yaml with tag
        run: |
          TAG_NAME=${{ github.ref_name }}
          sed -i "s/tag:.*/tag: ${TAG_NAME}/" backend-chart/values.yaml

      - name: Commit and Push changes
        run: |
          TAG_NAME=${{ github.ref_name }}
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git checkout main
          git add backend-chart/values.yaml
          git commit -m "Update values.yaml with image tag: ${TAG_NAME}"
          git push origin main

  frontend-deploy:
    if: startsWith(github.ref, 'refs/tags/')
    needs: update-values
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies and build frontend
        run: |
          cd fe
          npm install
          npm run build

      - name: Install Firebase CLI
        run: |
          npm install -g firebase-tools

      - name: Deploy Frontend to Firebase
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
        run: |
          cd fe
          firebase deploy --only hosting --project ${{ secrets.FIREBASE_PROJECT }}
