name: Java CI with Maven

on:
  push:
    branches: ["dev-backend"]
  pull_request:
    branches: ["dev-backend"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Create firebase.config.json
        # Creates firebase.config.json from secret
        run: |
           echo "${{ secrets.FIREBASE_CONFIG_JSON }}" | base64 -d > backend/src/main/resources/firebase.config.json
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build Docker image
        run: |
          cd backend
          docker build . -t ${{ secrets.DOCKERHUB_USERNAME }}/edtech-dockerfile:latest

      - name: Push Docker image to Docker Hub
        run: |
          cd backend
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/edtech-dockerfile:latest

